"""add_ticker_mentions

Revision ID: e91f584d8c59
Revises: b4605bca37fa
Create Date: 2026-05-16 17:30:23.405465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91f584d8c59'
down_revision: Union[str, None] = 'b4605bca37fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_mentions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('mention_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['raw_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticker_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticker_mentions_mention_date'), ['mention_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticker_mentions_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticker_mentions_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticker_mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticker_mentions_ticker'))
        batch_op.drop_index(batch_op.f('ix_ticker_mentions_source_id'))
        batch_op.drop_index(batch_op.f('ix_ticker_mentions_mention_date'))

    op.drop_table('ticker_mentions')
    # ### end Alembic commands ###
